from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('rtc-rx8010sj', src, depend = ['PKG_USING_RTC_RX8010SJ_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
