from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('rtc-rx8010sj', src, depend = ['PKG_USING_RTC_RX8010SJ'], CPPPATH = CPPPATH)

Return('group')
